# 共轭矩阵

In [1]:
import numpy as np
import scipy

In [10]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.ones((3,3))

In [11]:
Acj = A.conjugate(B)

In [12]:
print(Acj)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
