# CuPy基本使用

In [1]:
import numpy as np
import cupy as cp

In [2]:
print(cp.__version__)

5.0.0a1


In [3]:
x = cp.arange(6).reshape(2,3).astype('f')
print(x)

[[0. 1. 2.]
 [3. 4. 5.]]


In [4]:
y = cp.arange(3,dtype='f')

In [7]:
kernel = cp.ElementwiseKernel('float32 x,float32 y','float32 z','''
            if (x - 2 > y){
                z = x * y;
            }else{
                z = x + y;
            }
        ''')

In [8]:
res = kernel(x,y)
print(res)

[[ 0.  2.  4.]
 [ 0.  4. 10.]]


# 数据传输

## 传输数组数据到GPU

In [10]:
x_cpu = np.array([1,2,3])
x_gpu = cp.asarray(x_cpu)

## 传输数组到CPU

In [11]:
x_arr = x_gpu.get()
print(x_arr)

[1 2 3]


# 编写CPU/GPU Agnostic code

In [12]:
def softplus(x):
    xp = cp.get_array_module(x)
    return xp.maximum(0,x) + xp.log1p(xp.exp(-abs(x)))

In [13]:
x = np.arange(1,10)
res = softplus(x)
print(res)

[1.31326169 2.12692801 3.04858735 4.01814993 5.00671535 6.00247569
 7.00091147 8.00033541 9.0001234 ]
